// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6xRbARj20aJUJpHT_Qpg5GYTxqfq1cWQ',
    appId: '1:985202200278:web:cbba11c39f4ac599280377',
    messagingSenderId: '985202200278',
    projectId: 'my-e-list',
    authDomain: 'my-e-list.firebaseapp.com',
    storageBucket: 'my-e-list.firebasestorage.app',
    measurementId: 'G-FDSR06FK7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ZzNpfhky0E7ZrsxDEP1gT95mb9cv3uY',
    appId: '1:985202200278:android:6ee3e75bccf42ac4280377',
    messagingSenderId: '985202200278',
    projectId: 'my-e-list',
    storageBucket: 'my-e-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1MCxmlflAmd_NEF8ZpmuWjrCSZpoHQM',
    appId: '1:985202200278:ios:b87a1f57d2f799fe280377',
    messagingSenderId: '985202200278',
    projectId: 'my-e-list',
    storageBucket: 'my-e-list.firebasestorage.app',
    iosBundleId: 'com.alx.eShoppingList',
  );
}
